import type { VinciText } from './content'

// Full construction assumptions remain available in the intentionally opened record.
export const constructionRecords: Record<string, VinciText> = {
  slate: {en:'Slate appearance follows Q019/Q124/Q127: proposed .24 m widths [.18–.30] and .14 m exposures [.10–.18], with separate stone variation and fine cleft. The .24 m lead ridge cover [.18–.32] is a museum construction proposal. Damp spreads .07–.55 m from derived north-facing roof intersections; this weathering is conjectural, not an observation of 1517.',de:'Das Schieferbild folgt Q019/Q124/Q127: vorgeschlagene .24 m Breiten [.18–.30] und .14 m Deckhöhen [.10–.18], mit einzelnen Farbwechseln und feiner Spaltung. Die .24 m Bleifirstabdeckung [.18–.32] ist ein Bauvorschlag des Museums. Feuchte liegt .07–.55 m um abgeleitete nordgerichtete Dachschnittlinien; diese Alterung ist eine Vermutung, keine Beobachtung von 1517.'},
  retaining: {en:'The retaining-wall surface is a reconstruction choice informed by the tuffeau character in Q001/Q124: .62 × .30 m courses (ranges .45–.80 × .24–.38 m), 12 mm joints [8–18] and 2.5 mm joint relief [1–5]. Its bond and wear are proposed. The road-cut bank receives a proposed .22 m masonry lining [.16–.30] and a cap .035 m above the retained crest [.02–.05]; the mapped road and all IGN heights remain unchanged.',de:'Die Stützmaueroberfläche ist eine Rekonstruktionswahl nach dem Tuffeaucharakter in Q001/Q124: .62 × .30 m Schichten (Bereiche .45–.80 × .24–.38 m), 12 mm Fugen [8–18] und 2,5 mm Fugenrelief [1–5]. Verband und Alterung sind vorgeschlagen. Der Straßeneinschnitt erhält eine vorgeschlagene .22 m Mauerverkleidung [.16–.30] und eine Kappe .035 m über der erhaltenen Böschungskrone [.02–.05]; kartierte Straße und alle IGN-Höhen bleiben unverändert.'},
  chapel: {en:'The chapel has paired pointed lights and upper quadrilobe tracery (Q175). Their overall opening remains the 1.60 × 2.20 m proposal; the paired lancet height retains the printed 1.80 m. Curvature, a .46 m head rise [.35–.60], .085 m lobe radius [.065–.105] and plain fitted glazing are reconstruction choices; no modern painted glazing is reproduced.',de:'Die Kapelle hat zwei Spitzbogenlichter und einen oberen Vierpass (Q175). Die Gesamtöffnung bleibt der Vorschlag von 1,60 × 2,20 m; die Lanzetthöhe übernimmt die gedruckten 1,80 m. Krümmung, .46 m Bogenanstieg [.35–.60], .085 m Passradius [.065–.105] und eingepasstes Klarglas sind Rekonstruktionsentscheidungen; moderne Glasmalerei wird nicht wiedergegeben.'},
  glazing: {en:'Window recesses follow the registered openings. The 55 mm glazing rebate is a reconstruction choice within 35–90 mm; photographs Q124/Q127 establish recessed small panes, not that depth. Upper panes reflect the sky above a dark room; pane thickness 2–4 mm and IOR 1.45–1.55 are assumed.',de:'Die Fensternischen folgen den registrierten Öffnungen. Der Glasfalz von 55 mm ist eine Rekonstruktionswahl innerhalb 35–90 mm; Q124/Q127 belegen vertiefte kleine Scheiben, nicht diese Tiefe. Obere Scheiben spiegeln den Himmel über einem dunklen Raum; Scheibendicke 2–4 mm und IOR 1.45–1.55 sind angenommen.'},
}

// Each drawer paragraph names its evidence without exposing the catalogue keys.
export const evidenceWords: Record<string, VinciText> = {
  foundation: { en: 'The lower masonry follows the surviving walls down to the slope. Photographs of Clos Lucé guide its appearance; the buried footing is reconstructed.', de: 'Das untere Mauerwerk folgt den erhaltenen Mauern bis zum Hang. Fotografien von Clos Lucé leiten seine Gestaltung; das verdeckte Fundament ist rekonstruiert.' },
  minerals: { en: 'The photographs of Clos Lucé show thin red brick and pale, porous tuffeau. Their uneven colour and worn joints guide these reconstructed surfaces.', de: 'Die Fotografien von Clos Lucé zeigen dünne rote Ziegel und hellen, porösen Tuffeau. Ihre ungleichmäßige Farbe und verwitterten Fugen leiten diese rekonstruierten Oberflächen.' },
  finish: { en: 'The close grain of stone, plaster and wood is freely modelled. Material-library samples guide the finish, without claiming to preserve marks from this house.', de: 'Die feine Struktur von Stein, Putz und Holz ist frei gestaltet. Materialproben aus der Bibliothek leiten die Oberfläche, ohne Spuren dieses Hauses zu belegen.' },
  haze: { en: 'The distant ground fades into an imagined afternoon haze. The survey supplies the slope, but no source records the air of this minute.', de: 'Das ferne Gelände verschwindet in frei gestaltetem Nachmittagsdunst. Die Vermessung liefert den Hang, doch keine Quelle beschreibt die Luft dieser Minute.' },
  slate: { en: 'The roof photographs show overlapping slate with changing tones. The lead ridge and damp patches are reconstructed from that material character.', de: 'Die Dachfotografien zeigen überlappenden Schiefer mit wechselnden Farbtönen. Der Bleifirst und die feuchten Stellen sind nach diesem Materialbild rekonstruiert.' },
  retaining: { en: 'The survey fixes the slope beside the street. Tuffeau in the house photographs guides the reconstructed retaining wall and its coping.', de: 'Die Vermessung bestimmt den Hang neben der Straße. Der Tuffeau auf den Hausfotografien leitet die rekonstruierte Stützmauer und ihre Abdeckung.' },
  chapel: { en: 'The chapel photographs show paired pointed windows and a four-lobed opening above. Their stone tracery is reconstructed here with plain glass.', de: 'Die Kapellenfotografien zeigen zwei Spitzbogenfenster und darüber eine vierpassförmige Öffnung. Ihr steinernes Maßwerk ist hier mit klarem Glas rekonstruiert.' },
  glazing: { en: 'The house photographs show small panes set deep into the masonry. These reconstructed windows hold a dark room behind the glass and a little sky in the upper panes.', de: 'Die Hausfotografien zeigen kleine, tief im Mauerwerk sitzende Scheiben. Hinter diesen rekonstruierten Fenstern liegt ein dunkler Raum; die oberen Scheiben spiegeln etwas Himmel.' },
  collection: { en: 'These pavilions belong to the museum in our own century. The museum’s model places them below the garden; their rooms are still being built.', de: 'Diese Pavillons gehören zum Museum unseres Jahrhunderts. Das Museumsmodell setzt sie unterhalb des Gartens an; ihre Räume sind noch im Bau.' },
  collectionDesign: { en: 'The museum’s model sets a broad, low group of glass pavilions on slender posts. Their slate roofs and concrete base are a present-day design.', de: 'Das Museumsmodell sieht eine breite, niedrige Gruppe gläserner Pavillons auf schlanken Stützen vor. Schieferdächer und Betonsockel sind ein heutiger Entwurf.' },
  approach: { en: 'A new stair descends from the garden to the collection. Its route comes from the museum’s model and belongs to the present-day exhibition.', de: 'Eine neue Treppe führt vom Garten zur Sammlung hinab. Ihr Verlauf stammt aus dem Museumsmodell und gehört zur heutigen Ausstellung.' },
  access: { en: 'The connecting walk is a new museum route across the surveyed ground. Its landings and retaining edges are reconstructed for this visit.', de: 'Der Verbindungsweg ist ein neuer Museumsweg über das vermessene Gelände. Seine Podeste und Stützkanten sind für diesen Rundgang rekonstruiert.' },
  accessDesign: { en: 'The museum’s access plan joins the court to the garden stair. It preserves the surveyed slope around the new path.', de: 'Der Zugangsplan des Museums verbindet den Hof mit der Gartentreppe. Er erhält den vermessenen Hang neben dem neuen Weg.' },
  entry: { en: 'The entry is reconstructed from the surviving doorway and photographs. Its timber structure and inner surfaces are an arrangement made for this museum.', de: 'Der Eingang ist nach dem erhaltenen Portal und Fotografien rekonstruiert. Seine Holzkonstruktion und Innenflächen sind eine Gestaltung dieses Museums.' },
  entryFinish: { en: 'The entry’s lime plaster and clay floor follow the materials described in the building study. Their wear is imagined.', de: 'Kalkputz und Tonboden des Eingangs folgen den im Baubericht beschriebenen Materialien. Ihre Abnutzung ist frei gestaltet.' },
  road: { en: 'OpenStreetMap supplies the road’s course. Wheel tracks, loose gravel and straw suggest its use; no source records this surface in 1517.', de: 'OpenStreetMap liefert den Straßenverlauf. Fahrspuren, loser Kies und Stroh deuten ihre Nutzung an; keine Quelle belegt diese Oberfläche für 1517.' },
  court: { en: 'The courtyard follows the house photographs and the site survey. Its threshold and ground are reconstructed.', de: 'Der Hof folgt den Hausfotografien und der Geländevermessung. Seine Schwelle und sein Boden sind rekonstruiert.' },
  courtWear: { en: 'Gravel, wheel marks and a shallow drain give the courtyard signs of use. These details are imagined from the building’s setting.', de: 'Kies, Fahrspuren und eine flache Rinne geben dem Hof Gebrauchsspuren. Diese Einzelheiten sind nach der Umgebung des Hauses frei gestaltet.' },
  gate: { en: 'The house photographs guide the gate passage. Its wooden leaf and dark recess are reconstructed around the opening.', de: 'Die Hausfotografien leiten die Gestaltung des Tordurchgangs. Sein Holzflügel und seine dunkle Nische sind um die Öffnung rekonstruiert.' },
  roadGrade: { en: 'The reconstructed road meets the gate and rejoins the surveyed slope. OpenStreetMap fixes its course; its height in 1517 is unknown.', de: 'Die rekonstruierte Straße erreicht das Tor und schließt wieder an den vermessenen Hang an. OpenStreetMap bestimmt ihren Verlauf; ihre Höhe im Jahr 1517 ist unbekannt.' },
  apron: { en: 'A narrow strip of packed earth joins the house to the street. Its extent follows the measured walls and mapped road, while its historic surface remains unknown.', de: 'Ein schmaler Streifen gestampfter Erde verbindet Haus und Straße. Seine Ausdehnung folgt den vermessenen Mauern und der kartierten Straße; sein historischer Belag bleibt unbekannt.' },
  streetPath: { en: 'The street follows its present course on OpenStreetMap. An older route is plausible, but its paving is unknown.', de: 'Die Straße folgt ihrem heutigen Verlauf auf OpenStreetMap. Ein älterer Weg ist plausibel, doch sein Belag ist unbekannt.' },
  gardenPath: { en: 'The garden path is the museum’s own route down the surveyed slope. It does not claim to retrace a path from Leonardo’s time.', de: 'Der Gartenweg ist der eigene Weg des Museums den vermessenen Hang hinab. Er beansprucht nicht, einem Weg aus Leonardos Zeit zu folgen.' },
}
