/* THE STORY LAYER of this wing: one stop per station of the story card, in
 * the card's order, and the card's own chapter cuts between them. Every
 * displayed string here is the card's, copied and not written, so this file
 * is generated by `forge/story-import.mjs` and never edited by hand.
 * Nothing shows it yet: `forge/story-check.mjs` measures it against the
 * house's text law before a surface reads a word of it. */
import type { VinciCertainty, VinciText } from './content';

/** The card classes a stop in the wing's four words and in three more the
 *  story sheet adds, so the story's vocabulary is the wing's plus those. */
export type VinciStoryCertainty = VinciCertainty | 'tradition' | 'inferred' | 'disputed';

export interface VinciStoryStop {
  id: string;
  order: number;
  kind: 'station' | 'cut';
  /** the wing builds this station today */
  built: boolean;
  quiet: boolean;
  chapter: VinciText;
  age: VinciText | null;
  line: VinciText;
  drawer: VinciText | null;
  certainty: VinciStoryCertainty;
  /** the object the frame must show, as the card's frame names it */
  sees: string;
  /** canon sheet keys, or the card's own source ids where the sheet has no row */
  pointers: readonly string[];
}

export interface VinciStoryCanonRow {
  id: string;
  title: string;
}

export interface VinciStoryTitleWall {
  name: string;
  kicker: VinciText;
  prose: VinciText;
  buttons: readonly VinciText[];
}

export interface VinciStoryExit {
  things: readonly VinciText[];
  doors: readonly VinciText[];
}

export const vinciStory: readonly VinciStoryStop[] = [
  {
    id: "garden",
    order: 0,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "The last house, from below", de: "Das letzte Haus, von unten" },
    age: { en: "he is 65", de: "he is 65" },
    line: { en: "The house above you was Leonardo da Vinci's last. He wanted to see for himself how things work.", de: "Das Haus über dir war Leonardo da Vincis letztes. Er wollte mit eigenen Augen sehen, wie die Dinge funktionieren." },
    drawer: { en: "Above you is the house where he died. Behind you is a museum of what is left of him. It was built in our own century. The story starts long before either. He was born in 1452 and came here at 64. Everything you will see below was made in between.", de: "Über dir steht das Haus, in dem er starb. Hinter dir liegt ein Museum dessen, was von ihm blieb. Gebaut wurde es in unserer Zeit. Die Geschichte beginnt viel früher. Er wurde 1452 geboren und kam mit 64 hierher. Alles, was du unten siehst, entstand dazwischen." },
    certainty: "documented",
    sees: "The garden apron",
    pointers: ["C00", "C01", "C10", "C14"],
  },
  {
    id: "line-early",
    order: 1,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "The night he was born", de: "Die Nacht seiner Geburt" },
    age: { en: "age 0", de: "age 0" },
    line: { en: "Now the story goes back. He was born in 1452, and his grandfather wrote it down.", de: "Jetzt geht die Geschichte zurück. Er wurde 1452 geboren, und sein Großvater schrieb es auf." },
    drawer: { en: "Twelve dates of his life are cut into this floor. These are the first of them. He was born on 15 April 1452, at the third hour of the night. The hours were counted from nightfall, not from midnight. A tax return lists him at five as the son born outside marriage.", de: "Zwölf Daten seines Lebens sind in diesen Boden geschnitten. Das hier sind die ersten. Geboren wurde er am 15. April 1452, in der dritten Stunde der Nacht. Die Stunden zählte man ab Einbruch der Nacht, nicht ab Mitternacht. Eine Steuererklärung führt ihn mit fünf als unehelichen Sohn." },
    certainty: "documented",
    sees: "The dates cut into the gallery floor",
    pointers: ["C01", "C02"],
  },
  {
    id: "picture-room",
    order: 2,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "The pupil's angel", de: "Der Engel des Schülers" },
    age: { en: "about 20", de: "about 20" },
    line: { en: "It is said he painted an angel better than his master could. The master never painted again.", de: "Er soll einen Engel besser gemalt haben als sein Meister. Der Meister malte nie wieder." },
    drawer: { en: "This is the first picture on the wall. The wall runs in the order he made them. The panel is by him and his master Verrocchio together. Vasari printed the angel story in 1550, thirty years after Leonardo died. The museum that owns the panel still tells it. Nobody can prove it.", de: "Das ist das erste Bild an der Wand. Die Wand läuft in der Reihenfolge, in der er malte. Die Tafel stammt von ihm und seinem Meister Verrocchio. Vasari druckte die Geschichte vom Engel 1550, dreißig Jahre nach Leonardos Tod. Das Museum, dem die Tafel gehört, erzählt sie bis heute. Beweisen kann sie niemand." },
    certainty: "tradition",
    sees: "The east end of the hang",
    pointers: ["C03"],
  },
  {
    id: "picture-room-lisa",
    order: 3,
    kind: "station",
    built: false,
    quiet: false,
    chapter: { en: "A portrait he kept", de: "Ein Bildnis, das er behielt" },
    age: { en: "51", de: "51" },
    line: { en: "At 51 he was painting a woman from Florence. Her name was Lisa. Remember it.", de: "Mit 51 malte er eine Frau aus Florenz. Sie hieß Lisa. Merk dir den Namen." },
    drawer: { en: "In October 1503 a clerk in Florence wrote a note. Leonardo was painting the head of Lisa del Giocondo. The note names the woman, not a picture. Fourteen years later a visitor saw a Florentine woman's portrait and wrote no name. He said it was made for Giuliano de' Medici.", de: "Im Oktober 1503 hielt ein Schreiber in Florenz eine Notiz fest. Leonardo malte gerade den Kopf der Lisa del Giocondo. Die Notiz nennt die Frau, nicht ein Bild. Vierzehn Jahre später sah ein Besucher das Bildnis einer Florentinerin, ohne Namen. Gemalt sei es für Giuliano de' Medici." },
    certainty: "documented",
    sees: "The Mona Lisa's place in the hang",
    pointers: ["C04"],
  },
  {
    id: "picture-room-west",
    order: 4,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "Forty years of pictures", de: "Vierzig Jahre Bilder" },
    age: null,
    line: { en: "That was his whole life as a painter. Now the story goes back. He is thirty.", de: "Das war sein ganzes Leben als Maler. Jetzt geht die Geschichte zurück. Er ist dreißig." },
    drawer: { en: "Twenty-five pictures hang here, in the order he made them. Each hangs at the size its own museum records. Thirty-four metres from the first to the last. A few are copies by other hands, because his own are lost. Behind that door the story goes back to Milan.", de: "Fünfundzwanzig Bilder hängen hier, in der Reihenfolge ihrer Entstehung. Jedes hängt in dem Maß, das seine Sammlung verzeichnet. Vierunddreißig Meter vom ersten bis zum letzten. Einige sind Kopien fremder Hand, denn seine eigenen sind verloren. Hinter der Tür geht die Geschichte zurück nach Mailand." },
    certainty: "documented",
    sees: "The whole 34 m wall seen from its west end",
    pointers: ["D-PAINT:19", "TL:life-12"],
  },
  {
    id: "flight",
    order: 5,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "He wanted to fly", de: "Er wollte fliegen" },
    age: { en: "about 30", de: "about 30" },
    line: { en: "In Milan he drew machines like these. He wanted to fly. Nobody wrote down that he ever did.", de: "In Mailand zeichnete er solche Maschinen. Fliegen wollte er. Dass er je geflogen ist, hat niemand aufgeschrieben." },
    drawer: { en: "The letter offering his service survives as a copy. Nobody knows if it was sent. He drew this screw in a notebook. The sheet gives one size: four and a half metres from rim to middle. It does not say what turns it. To lift itself it needs about nineteen kilowatts. Four top cyclists make two.", de: "Der Brief, in dem er seine Dienste anbietet, ist nur als Abschrift erhalten. Ob er abgeschickt wurde, weiß niemand. Diese Schraube zeichnete er in ein Notizbuch. Das Blatt nennt nur ein Maß: viereinhalb Meter vom Rand bis zur Mitte. Wie sie angetrieben wird, steht nicht da. Zum Abheben bräuchte sie etwa neunzehn Kilowatt. Vier Spitzenradfahrer bringen zwei." },
    certainty: "inferred",
    sees: "The aerial screw at the middle of the hall",
    pointers: ["C05", "C07"],
  },
  {
    id: "works",
    order: 6,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "Seventeen years in Milan", de: "Siebzehn Jahre Mailand" },
    age: { en: "47", de: "47" },
    line: { en: "He stayed until he was 47. Then the French took Milan, and he left.", de: "Er blieb, bis er 47 war. Dann nahmen die Franzosen Mailand, und er ging." },
    drawer: { en: "Not everything here was his idea. Lock gates and the water screw existed before him. He drew them. He did not invent them. He also worked on a huge horse in clay. The bronze for it went to cannon instead. A man who remembered it wrote that soldiers shot at the horse.", de: "Nicht alles hier war seine Idee. Schleusentore und Wasserschraube gab es vor ihm. Er hat sie gezeichnet, nicht erfunden. Er arbeitete auch an einem riesigen Pferd aus Ton. Die Bronze dafür ging an Kanonen. Ein Mann, der sich erinnerte, schrieb, Soldaten hätten auf das Pferd geschossen." },
    certainty: "documented",
    sees: "The hall's other end",
    pointers: ["C06"],
  },
  {
    id: "reading-table",
    order: 7,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "Written backwards", de: "Rückwärts geschrieben" },
    age: null,
    line: { en: "He wrote his notebooks from right to left. A mirror reads them back. He never wrote down why.", de: "Seine Notizbücher schrieb er von rechts nach links. Ein Spiegel liest sie zurück. Warum, hat er nie aufgeschrieben." },
    drawer: { en: "What lies open is a printed copy from 1883. He was left-handed, and people who knew him wrote it down. Writing backwards keeps a left hand out of wet ink. That is our guess and not his. When he wrote for other people, he wrote the ordinary way. He filled book after book.", de: "Aufgeschlagen liegt ein gedruckter Nachdruck von 1883. Er war Linkshänder, Zeitgenossen haben das festgehalten. Rückwärts zu schreiben hält die linke Hand aus der nassen Tinte. Das ist unsere Vermutung, nicht seine. Für andere schrieb er ganz normal. Er füllte Buch um Buch." },
    certainty: "documented",
    sees: "The open page of the notebook on the table",
    pointers: ["BD:H14", "BD:M04", "D-MS:7"],
  },
  {
    id: "body",
    order: 8,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "Inside the body", de: "Im Inneren des Körpers" },
    age: { en: "near 60", de: "near 60" },
    line: { en: "At almost sixty he opened dead bodies and drew them. He wanted to see how we are made.", de: "Mit fast sechzig öffnete er Tote und zeichnete sie. Er wollte sehen, wie wir gebaut sind." },
    drawer: { en: "Twenty-nine sheets hang here, out of about six hundred at Windsor. On one sheet he wrote that all this would be finished in 1510. He drew the throat and noted this. Nobody can swallow and breathe at the same time. Try it. On one neck he drew eleven bones, where a neck has seven.", de: "Neunundzwanzig Blätter hängen hier, von etwa sechshundert in Windsor. Auf einem Blatt schrieb er, 1510 sei das alles fertig. Zum Hals notierte er das hier. Niemand kann gleichzeitig schlucken und atmen. Probier es. In einen Hals zeichnete er elf Knochen, ein Hals hat sieben." },
    certainty: "documented",
    sees: "The wall of 29 sheets along the gallery",
    pointers: ["C08"],
  },
  {
    id: "supper-wall",
    order: 9,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "A wall in Milan", de: "Eine Wand in Mailand" },
    age: { en: "45", de: "45" },
    line: { en: "The biggest picture of his that still exists is a wall in Milan. This is its size.", de: "Sein größtes Bild, das es noch gibt, ist eine Wand in Mailand. So groß ist es." },
    drawer: { en: "This field is the true size of the Last Supper. He finished it at 45. Four and a half metres high, almost nine across. The wall is in a dining hall in Milan. He painted it dry on the plaster instead of into it. In 1652 a doorway took the feet of Christ.", de: "Dieses Feld hat die wahre Größe des Abendmahls. Mit 45 wurde es fertig. Viereinhalb Meter hoch, fast neun breit. Die Wand steht in einem Speisesaal in Mailand. Er malte trocken auf den Putz statt in ihn hinein. 1652 nahm eine Türöffnung die Füße von Christus mit." },
    certainty: "documented",
    sees: "The court field at 4.6 by 8.8 m",
    pointers: ["C09"],
  },
  {
    id: "cut-amboise",
    order: 10,
    kind: "cut",
    built: false,
    quiet: false,
    chapter: { en: "Amboise. He is 64.", de: "Amboise. Er ist 64." },
    age: null,
    line: { en: "Amboise. He is 64.", de: "Amboise. Er ist 64." },
    drawer: null,
    certainty: "inferred",
    sees: "",
    pointers: ["C10"],
  },
  {
    id: "arrival",
    order: 11,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "A house in France", de: "Ein Haus in Frankreich" },
    age: { en: "64", de: "64" },
    line: { en: "At 64 he moved to France, to this house. It was the last house he lived in.", de: "Mit 64 zog er nach Frankreich, in dieses Haus. Es war das letzte Haus, in dem er lebte." },
    drawer: { en: "The royal castle stands 590 metres up the road. The king was Francis the First. The accounts record a pension of two thousand écus for two years. That the king also gave him this house is reported, not shown. The first record placing him here is dated 22 May 1517.", de: "Das königliche Schloss steht 590 Meter die Straße hinauf. Der König war Franz der Erste. Die Rechnungsbücher verzeichnen eine Pension von zweitausend Écus für zwei Jahre. Dass der König ihm auch dieses Haus gab, ist überliefert und nicht belegt. Der erste Beleg für ihn hier stammt vom 22. Mai 1517." },
    certainty: "inferred",
    sees: "The street under the royal château",
    pointers: ["C10"],
  },
  {
    id: "courtyard",
    order: 12,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "A visitor comes", de: "Ein Besucher kommt" },
    age: { en: "65", de: "65" },
    line: { en: "On 10 October 1517 a cardinal came to see him. His secretary called Leonardo the greatest painter of his time.", de: "Am 10. Oktober 1517 kam ein Kardinal zu Besuch. Sein Sekretär nannte Leonardo den größten Maler seiner Zeit." },
    drawer: { en: "The cardinal is Luigi d'Aragona, a grandson of a king of Naples. The party rode over from Tours after lunch. Over the door a bird spreads its wings above four words in stone. DIEV AVANT TOVT, God before everything. The day is written down. The hour is our choice.", de: "Der Kardinal heißt Luigi d'Aragona, ein Enkel eines Königs von Neapel. Die Gesellschaft ritt nach dem Mittagessen von Tours herüber. Über der Tür breitet ein Vogel die Flügel über vier Worte in Stein. DIEV AVANT TOVT, Gott vor allem. Der Tag ist belegt. Die Stunde haben wir gewählt." },
    certainty: "documented",
    sees: "The court and the house door",
    pointers: ["C11", "C12"],
  },
  {
    id: "hall",
    order: 13,
    kind: "station",
    built: true,
    quiet: true,
    chapter: { en: "The great hall", de: "Der große Saal" },
    age: null,
    line: { en: "Guests were received in the hall behind this door. It is said the king gave him this house.", de: "Hinter dieser Tür empfing man Gäste. Der König soll ihm dieses Haus gegeben haben." },
    drawer: { en: "The room is not open, so the house is shown from outside. The panelling and the chimneypiece in it today are eighteenth century. They came two hundred years after him. What the room looked like in his time, no source describes. The house itself has stood since the fifteenth century.", de: "Der Raum ist nicht geöffnet, deshalb zeigen wir das Haus von außen. Vertäfelung und Kamin darin stammen aus dem achtzehnten Jahrhundert. Sie kamen zweihundert Jahre nach ihm ins Haus. Wie der Saal zu seiner Zeit aussah, beschreibt keine Quelle. Das Haus selbst steht seit dem fünfzehnten Jahrhundert." },
    certainty: "reconstructed",
    sees: "The open house door at the hall's threshold",
    pointers: ["C10"],
  },
  {
    id: "oratory",
    order: 14,
    kind: "station",
    built: true,
    quiet: true,
    chapter: { en: "The small chapel", de: "Die kleine Kapelle" },
    age: null,
    line: { en: "This small chapel was here before he came. The paintings inside may be by his pupils.", de: "Diese kleine Kapelle stand schon, als er kam. Die Bilder darin stammen vielleicht von seinen Schülern." },
    drawer: { en: "The story goes that Charles the Eighth built it in 1492. It was for his queen, Anne of Brittany. No survey of the building has confirmed that year. The wall paintings are given to Leonardo's pupils. That has never been settled either. The room is not open, so the house is shown from outside.", de: "Karl der Achte soll sie 1492 gebaut haben, für seine Königin Anne de Bretagne. Eine Bauuntersuchung hat dieses Jahr nie bestätigt. Die Wandbilder werden Schülern Leonardos zugeschrieben. Auch das ist nicht geklärt. Der Raum ist nicht geöffnet, deshalb zeigen wir das Haus von außen." },
    certainty: "documented",
    sees: "The chapel window at the south end of the house",
    pointers: ["BD:W09", "D-PLACE:3"],
  },
  {
    id: "study",
    order: 15,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "What the secretary wrote", de: "Was der Sekretär aufschrieb" },
    age: { en: "65", de: "65" },
    line: { en: "The secretary wrote down a Florentine woman's picture, and no name. Leonardo's hand no longer painted, but it drew.", de: "Der Sekretär notierte ein Bild einer Frau aus Florenz, keinen Namen. Leonardos Hand malte nicht mehr, aber sie zeichnete." },
    drawer: { en: "He took Leonardo for a man over seventy. He was 65. The three pictures are a Florentine lady and a young Saint John. The third is a Virgin with Saint Anne. You walked past all three. Two months later the same man saw that wall in Milan. He wrote that it was already spoiling.", de: "Er hielt Leonardo für einen Mann von über siebzig. Er war 65. Die drei Bilder sind eine Florentinerin und ein junger Johannes. Das dritte ist eine Maria mit der heiligen Anna. An allen dreien bist du vorbeigegangen. Zwei Monate später sah derselbe Mann jene Wand in Mailand. Er schrieb, dass sie schon zu verderben anfing." },
    certainty: "documented",
    sees: "The study window and the court under it",
    pointers: ["C09", "C13"],
  },
  {
    id: "chamber",
    order: 16,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "The north room", de: "Das Nordzimmer" },
    age: { en: "67", de: "67" },
    line: { en: "He died in this house at 67. His room was probably at this end.", de: "Er starb in diesem Haus mit 67. Sein Zimmer lag wohl an diesem Ende." },
    drawer: { en: "The house museum puts his room at this end. That is a proposal, not a record. He died on 2 May 1519. His pupil Melzi wrote to the family a month later. He called Leonardo the best of fathers to him. Vasari later wrote that the king held his head. He also put his age at 75. He was 67.", de: "Das Hausmuseum vermutet sein Zimmer an diesem Ende. Das ist ein Vorschlag, kein Beleg. Er starb am 2. Mai 1519. Sein Schüler Melzi schrieb einen Monat später an die Familie. Für ihn war Leonardo der beste Vater. Vasari erzählte später, der König habe seinen Kopf gehalten. Er gab sein Alter mit 75 an. Er war 67." },
    certainty: "documented",
    sees: "The north end of the house",
    pointers: ["C03", "C14"],
  },
  {
    id: "cut-kings-castle",
    order: 17,
    kind: "cut",
    built: false,
    quiet: false,
    chapter: { en: "The king's castle", de: "Das Schloss des Königs" },
    age: null,
    line: { en: "The king's castle", de: "Das Schloss des Königs" },
    drawer: null,
    certainty: "documented",
    sees: "",
    pointers: ["C15", "C16"],
  },
  {
    id: "grave",
    order: 18,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "Where he lies", de: "Wo er liegt" },
    age: null,
    line: { en: "He wanted to be buried in a church nearby. It was pulled down. Nobody knows where he rests.", de: "Er wollte in einer Kirche hier in der Nähe begraben werden. Sie wurde abgerissen. Wo er liegt, weiß niemand." },
    drawer: { en: "He asked to be buried inside the church at the castle. He was probably buried there. Which day, nobody can show. The church came down in the early 1800s. A dig in 1863 found bones and broken stones with letters on them. The stone laid in 1874 says only that one supposes he is there.", de: "Er bat darum, in der Kirche beim Schloss begraben zu werden. Wahrscheinlich wurde er dort begraben. Welcher Tag es war, kann niemand zeigen. Die Kirche verschwand Anfang des 19. Jahrhunderts. Eine Grabung fand 1863 Knochen und Steinstücke mit Buchstaben. Auf dem Stein von 1874 steht nur, dass man ihn hier vermutet." },
    certainty: "documented",
    sees: "The slab in the grave court",
    pointers: ["C15", "C16"],
  },
];

export const vinciStoryCanon: readonly VinciStoryCanonRow[] = [
  { id: "C00", title: "The opening, the garden apron" },
  { id: "C01", title: "The birth" },
  { id: "C02", title: "The household at five" },
  { id: "C03", title: "The angel" },
  { id: "C04", title: "Lisa, and the picture of 1517" },
  { id: "C05", title: "The offer to Milan" },
  { id: "C06", title: "Milan, the years and the horse" },
  { id: "C07", title: "Flight, and the parachute" },
  { id: "C08", title: "The anatomy" },
  { id: "C09", title: "The Last Supper" },
  { id: "C10", title: "France, the pension, the house" },
  { id: "C11", title: "The visit of 10 October 1517" },
  { id: "C12", title: "The cardinal" },
  { id: "C13", title: "What the secretary wrote" },
  { id: "C14", title: "The death" },
  { id: "C15", title: "The will" },
  { id: "C16", title: "The grave" },
];

export const vinciStoryTitleWall: VinciStoryTitleWall = {
  name: "Leonardo da Vinci",
  kicker: { en: "CLOS LUCÉ, AMBOISE · 10 OCTOBER 1517, 15:19 BY THE SUN", de: "CLOS LUCÉ, AMBOISE · 10. OKTOBER 1517, 15:19 NACH DER SONNE" },
  prose: { en: "The house above you was the last he lived in. His story starts 65 years earlier. Everything of his that is left stands behind you.", de: "Das Haus über dir war das letzte, in dem er lebte. Seine Geschichte beginnt 65 Jahre früher. Alles, was von ihm blieb, steht hinter dir." },
  buttons: [{ en: "Begin", de: "Beginnen" }, { en: "Tell me the story", de: "Erzähl mir die Geschichte" }, { en: "Walk freely", de: "Frei umsehen" }],
};

export const vinciStoryExit: VinciStoryExit = {
  things: [
    { en: "He looked at everything himself: faces, water, birds, the human body.", de: "Er sah sich alles selbst an: Gesichter, Wasser, Vögel, den menschlichen Körper." },
    { en: "He left about seven thousand pages of notes, and many works unfinished.", de: "Er hinterließ rund siebentausend Seiten Notizen und viele unvollendete Werke." },
    { en: "He died in France in 1519. Nobody is sure where he lies.", de: "Er starb 1519 in Frankreich. Wo er liegt, weiß niemand sicher." },
  ],
  doors: [
    { en: "Ask him yourself", de: "Frag ihn selbst" },
    { en: "Another life", de: "Ein anderes Leben" },
  ],
};

export function vinciStoryStop(id: string): VinciStoryStop | undefined {
  return vinciStory.find((stop) => stop.id === id);
}
