/* THE STORY LAYER of this wing: one stop per station of the story card, in
 * the card's order, and the card's own chapter cuts between them. Every
 * displayed string here is the card's, copied and not written, so this file
 * is generated by `forge/story-import.mjs` and never edited by hand.
 * Nothing shows it yet: `forge/story-check.mjs` measures it against the
 * house's text law before a surface reads a word of it. */
import type { VinciCertainty, VinciText } from './content';

/** The card classes a stop in the wing's four words and in three more the
 *  story sheet adds, so the story's vocabulary is the wing's plus those. */
export type VinciStoryCertainty = VinciCertainty | 'tradition' | 'inferred' | 'disputed';

export interface VinciStoryStop {
  id: string;
  order: number;
  kind: 'station' | 'cut';
  /** the wing builds this station today */
  built: boolean;
  quiet: boolean;
  chapter: VinciText;
  age: VinciText | null;
  line: VinciText;
  drawer: VinciText | null;
  certainty: VinciStoryCertainty;
  /** the object the frame must show, as the card's frame names it */
  sees: string;
  /** canon sheet keys, or the card's own source ids where the sheet has no row */
  pointers: readonly string[];
}

export interface VinciStoryCanonRow {
  id: string;
  title: string;
}

export interface VinciStoryTitleWall {
  name: string;
  kicker: VinciText;
  prose: VinciText;
  buttons: readonly VinciText[];
}

export interface VinciStoryExit {
  things: readonly VinciText[];
  doors: readonly VinciText[];
}

export const vinciStory: readonly VinciStoryStop[] = [
  {
    id: "garden",
    order: 0,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "His last house", de: "Sein letztes Haus" },
    age: { en: "he is 65", de: "mit 65 Jahren" },
    line: { en: "He wanted to see everything himself: faces, water, birds, the inside of the body.", de: "Er wollte alles mit eigenen Augen sehen: Gesichter, Wasser, Vögel, das Innere des Körpers." },
    drawer: { en: "That is our reading of one notebook line: wisdom is the daughter of experience. The page is in London, and the note breaks off. All four wait behind you, in a museum of our century. The faces hang in the picture room. Water and birds are in the machine hall. The inside of the body fills a wall of sheets.", de: "So lesen wir eine Zeile in seinen Notizbüchern: Weisheit ist die Tochter der Erfahrung. Die Seite liegt heute in London, und die Notiz bricht mittendrin ab. Alle vier warten hinter dir, in einem Museum, erbaut in unserem Jahrhundert. Die Gesichter hängen im Bildersaal. Wasser und Vögel sind in der Maschinenhalle. Das Innere des Körpers füllt eine Wand voller Blätter." },
    certainty: "documented",
    sees: "The garden apron",
    pointers: ["C00", "C01", "C08", "C10", "C14"],
  },
  {
    id: "line-early",
    order: 1,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "The night he was born", de: "Die Nacht seiner Geburt" },
    age: { en: "age 0", de: "Geburt" },
    line: { en: "Now the story goes back, to the day he was born. His grandfather wrote it down: a Saturday, at night.", de: "Jetzt geht die Geschichte zurück, zu seiner Geburt. Sein Großvater schrieb sie auf: ein Samstag, nachts." },
    drawer: { en: "Twelve dates are cut into this floor, and these are the first. The note says 15 April 1452, at the third hour of the night. Those hours ran from nightfall, not midnight. One mark says tradition: Anchiano, said to be his birthplace. The note names no place. A tax return lists him at five as a son born outside marriage.", de: "Zwölf Daten sind in diesen Boden eingelassen, das hier sind die ersten. Die Notiz nennt den 15. April 1452, die dritte Stunde der Nacht. Diese Stunden zählte man ab Einbruch der Nacht, nicht ab Mitternacht. Bei einer Markierung steht Überlieferung: Anchiano, das als sein Geburtsort gilt. Die Notiz nennt keinen Ort. Eine Steuererklärung führt ihn mit fünf als unehelichen Sohn." },
    certainty: "documented",
    sees: "The dates cut into the gallery floor",
    pointers: ["C01", "C02"],
  },
  {
    id: "picture-room",
    order: 2,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "The pupil's angel", de: "Der Engel des Schülers" },
    age: { en: "about 20", de: "mit etwa 20 Jahren" },
    line: { en: "It is said he painted one angel in this picture better than his master. The master never painted again.", de: "Er soll einen Engel in diesem Bild besser gemalt haben als sein Meister. Der Meister malte nie wieder." },
    drawer: { en: "This is the first picture on the wall. The angel is the one at the left, holding the robes. The panel is by him and his master Verrocchio. Vasari printed the story in 1550, thirty years after Leonardo died. He wrote the master was angry that a boy knew more. The panel's museum still tells it. Nobody can prove it.", de: "Das ist das erste Bild an der Wand. Der Engel ist der linke, der die Gewänder hält. Die Tafel stammt von ihm und seinem Meister Verrocchio. Vasari druckte die Geschichte 1550, dreißig Jahre nach Leonardos Tod. Er schrieb, den Meister habe geärgert, dass ein Junge mehr wusste. Das Museum, dem die Tafel gehört, erzählt sie weiter. Beweisen kann das niemand." },
    certainty: "tradition",
    sees: "The east end of the hang",
    pointers: ["C03"],
  },
  {
    id: "picture-room-lisa",
    order: 3,
    kind: "station",
    built: false,
    quiet: false,
    chapter: { en: "A woman called Lisa", de: "Eine Frau namens Lisa" },
    age: { en: "51", de: "mit 51 Jahren" },
    line: { en: "Decades later he was painting a woman from Florence. A clerk wrote her name down: Lisa. Remember that name.", de: "Jahrzehnte später malte er eine Frau aus Florenz. Ein Schreiber notierte ihren Namen: Lisa. Merk dir den Namen." },
    drawer: { en: "What hangs here is an old print. The painting is in Paris. In Florence, in October 1503, the clerk wrote in the margin of a book. The note says Leonardo was at work on a head of Lisa del Giocondo. The name the picture carries today stands in a book printed in 1550. That book spells Mona with one n.", de: "Hier hängt ein alter Kunstdruck. Das Gemälde selbst ist in Paris. Die Notiz entstand im Oktober 1503 in Florenz, am Rand eines Buches. Dort steht, Leonardo arbeite an einem Kopf der Lisa del Giocondo. Der Name, den das Bild heute trägt, steht in einem Buch von 1550. Das Buch schreibt Mona mit einem n." },
    certainty: "documented",
    sees: "The Mona Lisa's place in the hang",
    pointers: ["C04"],
  },
  {
    id: "picture-room-west",
    order: 4,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "Where the pictures end", de: "Wo die Bilder enden" },
    age: null,
    line: { en: "Here the pictures end. Now the story goes back. He is about thirty and new in Milan.", de: "Hier enden die Bilder. Jetzt geht die Geschichte zurück. Er ist etwa dreißig und neu in Mailand." },
    drawer: { en: "Twenty-five pictures hang on this wall, roughly in the order he made them. Each hangs close to its real size. Thirty-four metres from first to last. One is a copy by other hands, because his own is lost. The last one is from his workshop and not his own hand. He left Florence with one big picture here unfinished.", de: "Fünfundzwanzig Bilder hängen hier, ungefähr in der Reihenfolge, in der sie entstanden. Jedes hängt etwa in seiner wirklichen Größe. Vierunddreißig Meter vom ersten bis zum letzten. Eines ist eine Kopie von anderer Hand, denn sein eigenes ist verloren. Das letzte stammt aus seiner Werkstatt, nicht von seiner eigenen Hand. Ein großes Bild hier ließ er unvollendet, als er Florenz verließ." },
    certainty: "documented",
    sees: "The whole 34 m wall seen from its west end",
    pointers: ["C05"],
  },
  {
    id: "flight",
    order: 5,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "He wanted to fly", de: "Er wollte fliegen" },
    age: { en: "about 30", de: "mit etwa 30 Jahren" },
    line: { en: "There he drew machines like these. He wanted to fly. Nobody wrote down that he ever did.", de: "Dort zeichnete er solche Maschinen. Fliegen wollte er. Dass er je geflogen ist, hat niemand aufgeschrieben." },
    drawer: { en: "The letter offering Milan's duke his service survives as a copy. Nobody knows if it was sent. He drew this screw in a notebook. The sheet gives one size: four and a half metres, rim to middle. It does not say what turns it. We estimate it needs about nineteen kilowatts to lift itself. Four top cyclists together make two.", de: "Sein Angebot an den Herzog von Mailand ist nur als Abschrift erhalten. Ob es je abgeschickt wurde, weiß niemand. Diese Schraube zeichnete er in ein Notizbuch. Das Blatt nennt nur ein Maß: viereinhalb Meter vom Rand zur Mitte. Wie sie angetrieben wird, steht nicht da. Wir schätzen, zum Abheben bräuchte sie etwa neunzehn Kilowatt. Vier Spitzenradfahrer schaffen zusammen etwa zwei." },
    certainty: "inferred",
    sees: "The aerial screw at the middle of the hall",
    pointers: ["C05", "C07"],
  },
  {
    id: "works",
    order: 6,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "The French take Milan", de: "Die Franzosen nehmen Mailand ein" },
    age: { en: "47", de: "mit 47 Jahren" },
    line: { en: "He drew machines for water too, and stayed for about seventeen years. Then the French took Milan, and he left.", de: "Er zeichnete auch Wassermaschinen und blieb etwa siebzehn Jahre. Dann nahmen die Franzosen Mailand ein, und er ging." },
    drawer: { en: "Not everything here was his idea. Lock gates and the water screw were in use before he was born. He also worked on a huge horse in clay, meant for bronze. The bronze for it went to cannon instead. A man who remembered it wrote, decades later, that soldiers shot at the horse.", de: "Nicht alles hier war seine Idee. Schleusentore und die Wasserschraube waren schon in Gebrauch, als er geboren wurde. Er arbeitete auch an einem riesigen Tonpferd, das in Bronze gegossen werden sollte. Die Bronze dafür wurde zu Kanonen gegossen. Einer, der sich daran erinnerte, schrieb Jahrzehnte später, Soldaten hätten auf das Pferd geschossen." },
    certainty: "documented",
    sees: "The hall's other end",
    pointers: ["C06"],
  },
  {
    id: "reading-table",
    order: 7,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "Written backwards", de: "Rückwärts geschrieben" },
    age: null,
    line: { en: "He wrote his notebooks from right to left. A mirror reads them back. He never wrote down why.", de: "Seine Notizbücher schrieb er von rechts nach links. Im Spiegel werden sie lesbar. Warum, hat er nie aufgeschrieben." },
    drawer: { en: "What lies open is a printed copy from 1883. The flying screw comes from this same notebook. People who knew him wrote down that he was left-handed. Writing backwards keeps a left hand out of wet ink. That is our guess, not his. When he wrote for other people, he wrote the ordinary way. He filled book after book.", de: "Aufgeschlagen liegt ein Nachdruck von 1883. Auch die Luftschraube stammt aus diesem Notizbuch. Leute, die ihn kannten, schrieben auf, dass er Linkshänder war. Rückwärts zu schreiben hält die linke Hand aus der nassen Tinte. Das ist unsere Vermutung, nicht seine. Für andere schrieb er ganz normal. Er füllte Buch um Buch." },
    certainty: "documented",
    sees: "The open page of the notebook on the table",
    pointers: ["BD:H14", "BD:M04", "D-MS:7"],
  },
  {
    id: "body",
    order: 8,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "Inside the body", de: "Im Inneren des Körpers" },
    age: { en: "near 60", de: "mit fast 60 Jahren" },
    line: { en: "Later he opened dead bodies and drew what he found. He wanted to see the inside for himself.", de: "Später öffnete er Tote und zeichnete, was er fand. Er wollte das Innere mit eigenen Augen sehen." },
    drawer: { en: "Windsor holds about six hundred of his sheets. Twenty-nine hang here. On one he wrote he believed all this would be done in 1510. He told a visitor he had opened over thirty bodies. A sheet of the throat says nobody can swallow and breathe at once. Try it. He gave one neck eleven bones, where a neck has seven.", de: "In Windsor liegen etwa sechshundert seiner Blätter. Neunundzwanzig hängen hier. Auf einem schrieb er, er glaube, 1510 werde er mit all dem fertig sein. Einem Besucher sagte er, er habe mehr als dreißig Tote geöffnet. Ein Blatt zur Kehle sagt: Niemand kann gleichzeitig schlucken und atmen. Probier es. In einen Hals zeichnete er elf Knochen, ein Hals hat sieben." },
    certainty: "documented",
    sees: "The wall of 29 sheets along the gallery",
    pointers: ["C08"],
  },
  {
    id: "supper-wall",
    order: 9,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "A wall in Milan", de: "Eine Wand in Mailand" },
    age: { en: "45", de: "mit 45 Jahren" },
    line: { en: "His biggest surviving picture is this big. He painted it on a wall in Milan, before the French came.", de: "Sein größtes erhaltenes Bild ist so groß. Er malte es auf eine Wand in Mailand, bevor die Franzosen kamen." },
    drawer: { en: "This field is the Last Supper's true size. Four and a half metres high, almost nine across. The wall is in the dining hall of a monastery. The duke pressed him to finish it, and he did at 45. He painted it dry on the plaster, not into it. In 1652 a doorway took the feet of Christ.", de: "Dieses Feld hat die wahre Größe des Abendmahls. Viereinhalb Meter hoch, fast neun breit. Die Wand steht im Speisesaal eines Klosters. Der Herzog drängte ihn, es zu vollenden, und mit 45 war es fertig. Er malte trocken auf den Putz, nicht in ihn hinein. 1652 nahm eine Türöffnung die Füße Christi mit." },
    certainty: "documented",
    sees: "The court field at 4.6 by 8.8 m",
    pointers: ["C09"],
  },
  {
    id: "cut-now-to-france-and-his-last-house",
    order: 10,
    kind: "cut",
    built: false,
    quiet: false,
    chapter: { en: "Now to France, and his last house.", de: "Jetzt nach Frankreich, in sein letztes Haus." },
    age: null,
    line: { en: "Now to France, and his last house.", de: "Jetzt nach Frankreich, in sein letztes Haus." },
    drawer: null,
    certainty: "inferred",
    sees: "",
    pointers: ["C10"],
  },
  {
    id: "arrival",
    order: 11,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "The king's painter", de: "Der Maler des Königs" },
    age: { en: "64", de: "mit 64 Jahren" },
    line: { en: "He moved to France, into this house. The French king paid him, and he was the king's painter.", de: "Er zog nach Frankreich, in dieses Haus. Der französische König bezahlte ihn: Er war der Maler des Königs." },
    drawer: { en: "The royal castle stands 590 metres up the road. The king was Francis the First, then about 22. His accounts record a pension of two thousand écus for two years. That he also gave him this house is reported, not shown. No record gives the day he arrived. The earliest known record of him here is dated 22 May 1517.", de: "Das königliche Schloss steht 590 Meter die Straße hinauf. Der König war Franz der Erste, damals etwa 22. Seine Rechnungsbücher verzeichnen eine Pension von zweitausend Écus für zwei Jahre. Dass er ihm auch dieses Haus gab, ist überliefert, nicht belegt. Den Tag seiner Ankunft nennt keine Quelle. Der früheste bekannte Nachweis, dass er hier war, stammt vom 22. Mai 1517." },
    certainty: "inferred",
    sees: "The street under the royal château",
    pointers: ["C10"],
  },
  {
    id: "courtyard",
    order: 12,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "A visitor comes", de: "Ein Besucher kommt" },
    age: { en: "65", de: "mit 65 Jahren" },
    line: { en: "The visitor was a cardinal. His secretary wrote it down, and called Leonardo the best painter of his time.", de: "Der Besucher war ein Kardinal. Sein Sekretär schrieb es auf und nannte Leonardo den besten Maler seiner Zeit." },
    drawer: { en: "The cardinal was Luigi d'Aragona, a grandson of a king of Naples. His secretary was Antonio de Beatis. The party rode over from Tours after lunch. Over the door a bird spreads its wings above three words in stone. DIEV AVANT TOVT, God before everything. The day is written down and the hour is our choice.", de: "Der Kardinal war Luigi d'Aragona, ein Enkel eines Königs von Neapel. Sein Sekretär hieß Antonio de Beatis. Die Reisenden ritten nach dem Mittagessen von Tours herüber. Über der Tür breitet ein Vogel die Flügel über drei Worten in Stein. DIEV AVANT TOVT, Gott vor allem. Der Tag ist belegt, die Stunde haben wir gewählt." },
    certainty: "documented",
    sees: "The court and the house door",
    pointers: ["C11", "C12"],
  },
  {
    id: "hall",
    order: 13,
    kind: "station",
    built: true,
    quiet: true,
    chapter: { en: "The great hall", de: "Der große Saal" },
    age: null,
    line: { en: "We rebuilt this hall, which nobody described in his time. It is said the king gave him the house.", de: "Wir haben diesen Saal nachgebaut, den zu seiner Zeit niemand beschrieb. Der König soll ihm das Haus geschenkt haben." },
    drawer: { en: "The pension is in the king's accounts. The house is not. The tiles lie diagonally, as a photograph of the room shows. The fireplace there was changed in the eighteenth century. So ours takes a form of about 1500. The table, chest and stools copy furniture of his time, and none was his.", de: "Die Pension steht in den Rechnungsbüchern des Königs. Das Haus steht nicht darin. Die Fliesen liegen diagonal, wie eine Fotografie des Raums zeigt. Der Kamin dort wurde im achtzehnten Jahrhundert verändert. Unserer hat deshalb eine Form um 1500. Tisch, Truhe und Hocker sind nach Möbeln seiner Zeit gebaut. Keines davon gehörte ihm." },
    certainty: "reconstructed",
    sees: "The great hall from inside its door",
    pointers: ["C10"],
  },
  {
    id: "oratory",
    order: 14,
    kind: "station",
    built: true,
    quiet: true,
    chapter: { en: "The small chapel", de: "Die kleine Kapelle" },
    age: null,
    line: { en: "This small chapel was here before he came. The paintings inside may be by his pupils.", de: "Diese kleine Kapelle stand schon, als er kam. Die Bilder darin stammen vielleicht von seinen Schülern." },
    drawer: { en: "The story goes that King Charles the Eighth built it in 1492. It was for his queen, Anne of Brittany. No survey of the building has confirmed that year. Whether Leonardo's pupils painted the walls has never been settled. The room is not open, so the house is shown from outside. The pointed window is the chapel's.", de: "Karl der Achte soll sie 1492 gebaut haben, für seine Königin Anne de Bretagne. Eine Bauuntersuchung hat dieses Jahr nie bestätigt. Ob Leonardos Schüler die Wände bemalten, ist nie geklärt worden. Der Raum ist nicht geöffnet, deshalb zeigen wir das Haus von außen. Das spitze Fenster gehört zur Kapelle." },
    certainty: "documented",
    sees: "The chapel window at the south end of the house",
    pointers: ["BD:W09", "D-PLACE:3"],
  },
  {
    id: "study",
    order: 15,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "What the secretary wrote", de: "Was der Sekretär aufschrieb" },
    age: { en: "65", de: "mit 65 Jahren" },
    line: { en: "The secretary saw a Florentine woman's picture, no name. Leonardo's hand could not paint as before, but still drew.", de: "Der Sekretär notierte: eine Florentinerin, ohne Namen. Leonardos Hand malte nicht mehr wie früher, zeichnete aber noch." },
    drawer: { en: "He took Leonardo for a man over seventy. He was 65. The woman's picture, he wrote, was made for Giuliano de' Medici. The other two showed a young Saint John and a Virgin with Saint Anne. You walked past pictures of all three. Two months later he saw that wall in Milan and found it already spoiling.", de: "Er hielt Leonardo für einen Mann über siebzig. Er war 65. Das Bild der Frau, schrieb er, sei für Giuliano de' Medici gemalt worden. Die anderen zwei zeigten einen jungen Johannes und Maria mit der heiligen Anna. Von allen dreien hängt ein Bild im Bildersaal. Zwei Monate später sah er jene Wand in Mailand, und sie nahm schon Schaden." },
    certainty: "documented",
    sees: "The study window and the court under it",
    pointers: ["C04", "C09", "C13"],
  },
  {
    id: "chamber",
    order: 16,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "Where he died", de: "Wo er starb" },
    age: { en: "67", de: "mit 67 Jahren" },
    line: { en: "He died in this house. His pupil wrote to Leonardo's brothers: to me he was the best of fathers.", de: "Er starb in diesem Haus. Sein Schüler schrieb an Leonardos Brüder: Für mich war er der beste Vater." },
    drawer: { en: "The house museum places his room at this end. That is a proposal, not a record. He died on 2 May 1519. The pupil, Francesco Melzi, wrote a month later. Leonardo's will had left him all his books, with his tools and drawings. Vasari wrote later that the king held his head, giving his age as 75. He was 67.", de: "Das Hausmuseum vermutet sein Zimmer an diesem Ende. Das ist ein Vorschlag, kein Beleg. Er starb am 2. Mai 1519. Der Schüler, Francesco Melzi, schrieb einen Monat später. Leonardos Testament hatte ihm alle Bücher vermacht, dazu Werkzeuge und Zeichnungen. Vasari schrieb später, der König habe seinen Kopf gehalten, als er mit 75 starb. Er war 67." },
    certainty: "documented",
    sees: "The north end of the house",
    pointers: ["C00", "C03", "C14", "C15"],
  },
  {
    id: "cut-kings-castle-up-the-road",
    order: 17,
    kind: "cut",
    built: false,
    quiet: false,
    chapter: { en: "The king's castle, up the road", de: "Das Schloss des Königs, die Straße hinauf" },
    age: null,
    line: { en: "The king's castle, up the road", de: "Das Schloss des Königs, die Straße hinauf" },
    drawer: null,
    certainty: "documented",
    sees: "",
    pointers: ["C15", "C16"],
  },
  {
    id: "grave",
    order: 18,
    kind: "station",
    built: true,
    quiet: false,
    chapter: { en: "Where he rests", de: "Wo er liegt" },
    age: null,
    line: { en: "He asked for a grave in the castle church. It was pulled down. Nobody is sure where he rests.", de: "Er bat um ein Grab in der Kirche beim Schloss. Sie wurde abgerissen. Wo er liegt, weiß niemand sicher." },
    drawer: { en: "The wish stands in his will, made nine days before he died. He was probably buried there, but which day, nobody can show. The church came down in the early 1800s. A dig in 1863 found bones. Two metres away, in the rubble, lay a stone reading LEO. The stone of 1874 says only that one supposes he is there.", de: "Der Wunsch steht in seinem Testament, neun Tage vor seinem Tod aufgesetzt. Wahrscheinlich wurde er dort begraben, doch den Tag kann niemand belegen. Die Kirche stand bis Anfang des 19. Jahrhunderts. Eine Grabung fand 1863 Knochen. Zwei Meter daneben, im Schutt, lag ein Stein mit dem Wort LEO. Auf dem Stein von 1874 steht nur, dass man ihn hier vermutet." },
    certainty: "documented",
    sees: "The slab in the grave court",
    pointers: ["C15", "C16"],
  },
];

export const vinciStoryCanon: readonly VinciStoryCanonRow[] = [
  { id: "C00", title: "The opening, the garden apron" },
  { id: "C01", title: "The birth" },
  { id: "C02", title: "The household at five" },
  { id: "C03", title: "The angel" },
  { id: "C04", title: "Lisa, and the picture of 1517" },
  { id: "C05", title: "The offer to Milan" },
  { id: "C06", title: "Milan, the years and the horse" },
  { id: "C07", title: "Flight, and the parachute" },
  { id: "C08", title: "The anatomy" },
  { id: "C09", title: "The Last Supper" },
  { id: "C10", title: "France, the pension, the house" },
  { id: "C11", title: "The visit of 10 October 1517" },
  { id: "C12", title: "The cardinal" },
  { id: "C13", title: "What the secretary wrote" },
  { id: "C14", title: "The death" },
  { id: "C15", title: "The will" },
  { id: "C16", title: "The grave" },
];

export const vinciStoryTitleWall: VinciStoryTitleWall = {
  name: "Leonardo da Vinci",
  kicker: { en: "CLOS LUCÉ, AMBOISE · 10 OCTOBER 1517, 15:19 BY THE SUN", de: "CLOS LUCÉ, AMBOISE · 10. OKTOBER 1517, 15:19 NACH DER SONNE" },
  prose: { en: "Leonardo da Vinci lived in the house above you. On this day a visitor came to see him. What the visitor wrote down waits for you inside. Behind you is a museum of what he left.", de: "Leonardo da Vinci wohnte im Haus über dir. An diesem Tag kam ein Besucher zu ihm. Was der Besucher aufschrieb, wartet drinnen auf dich. Hinter dir steht ein Museum seiner Werke." },
  buttons: [{ en: "Begin", de: "Beginnen" }, { en: "Tell me the story", de: "Erzähl mir die Geschichte" }, { en: "Walk freely", de: "Frei umsehen" }],
};

export const vinciStoryExit: VinciStoryExit = {
  things: [
    { en: "He looked at everything himself: faces, water, birds, the inside of the body.", de: "Er sah sich alles selbst an: Gesichter, Wasser, Vögel, das Innere des Körpers." },
    { en: "He left about seven thousand pages of notes, and many works unfinished.", de: "Er hinterließ rund siebentausend Seiten Notizen und viele unvollendete Werke." },
    { en: "He died in France at 67. Nobody is sure where he rests.", de: "Er starb mit 67 in Frankreich. Wo er liegt, weiß niemand sicher." },
  ],
  doors: [
    { en: "Ask Leonardo", de: "Frag Leonardo" },
    { en: "Another life", de: "Ein anderes Leben" },
  ],
};

export function vinciStoryStop(id: string): VinciStoryStop | undefined {
  return vinciStory.find((stop) => stop.id === id);
}
